defaults:
  - default
  - _self_

# Override from `default` config
id: carla_env
action_repeat: 1
capture_video: False
reward_as_observation: True

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.carla_env.CarlaEnv
  id: ${env.id}
  screen_size: ${env.screen_size}
  seed: ${seed}
